name: CI

on:
  - push
  - pull_request

jobs:
  unit-test:
    name: Unit Test

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout myself
        uses: actions/checkout@v3
      - name: Install myself
        run: python setup.py install
      - name: Run unit tests
        run: python -m unittest
