name: CI

on:
  - push
  - pull_request

jobs:
  unit-test:
    name: Unit Test

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout myself
        uses: actions/checkout@v4
      - name: Install setuptools
        run: pip install --upgrade setuptools
      - name: Install myself
        run: python setup.py install
      - name: Run unit tests
        run: python -m unittest

  release:
    name: Release

    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install setuptools and wheel
        run: pip install --upgrade setuptools wheel
      - name: Checkout myself
        uses: actions/checkout@v4
      - name: Install myself
        run: python setup.py install
      - name: Run unit tests
        run: python -m unittest
      - name: Build dist
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
